### ISSUE TITLE
GPA0.0の場合

### ISSUE THREAD

**Issue by hoppiece** [ushitora-anqou/GPA-Pokemon#5]
## About
GPA が0.0の場合に正しく動作しない模様
## Reference
https://twitter.com/1hor_/status/1298130887230369793?s=20
> GPA0だから対応する図鑑番号0のポケモンが居なくてデータの正しさを疑われるのホンマにしにたい

**Comment by mori97** [comment]
ワロタ

**Comment by ushitora-anqou** [comment]
Fixed #6
